# Generated by Django 5.0.14 on 2025-05-17 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, unique=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Ipress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del registro')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código único')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoría')),
                ('departamento', models.CharField(max_length=50, verbose_name='Departamento')),
                ('provincia', models.CharField(max_length=50, verbose_name='Provincia')),
                ('disa', models.CharField(max_length=50, verbose_name='DISA')),
                ('distrito', models.CharField(max_length=50, verbose_name='Distrito')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('responsable', models.CharField(max_length=100, verbose_name='Responsable de la Ipress')),
                ('monitor', models.CharField(max_length=100, verbose_name='Monitor')),
            ],
            options={
                'verbose_name': 'Ipress',
                'verbose_name_plural': 'Ipresses',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Texto de la pregunta')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ficha.categoriapregunta', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cumplimiento', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No'), ('NA', 'No aplica')], max_length=2, verbose_name='Cumple')),
                ('puntaje', models.PositiveIntegerField(default=0, verbose_name='Puntaje')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('riesgos_problemas', models.TextField(blank=True, null=True, verbose_name='Riesgos/Problemas')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
    ]
