# Generated by Django 5.0.14 on 2025-05-19 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipress',
            options={'verbose_name': 'Ipress', 'verbose_name_plural': 'Ipresses'},
        ),
        migrations.RemoveField(
            model_name='ipress',
            name='fecha',
        ),
        migrations.AddField(
            model_name='respuesta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 00:00:00', verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuesta',
            name='ipress',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='ficha.ipress'),
            preserve_default=False,
        ),
    ]
