# Generated by Django 5.0.14 on 2025-05-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0002_alter_ipress_options_remove_ipress_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipress',
            name='monitor',
        ),
        migrations.RemoveField(
            model_name='ipress',
            name='responsable',
        ),
        migrations.AddField(
            model_name='respuesta',
            name='monitor',
            field=models.CharField(default=1, max_length=100, verbose_name='Monitor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuesta',
            name='responsable',
            field=models.CharField(default=1, max_length=100, verbose_name='Responsable de la Ipress'),
            preserve_default=False,
        ),
    ]
