# Generated by Django 5.0.14 on 2025-05-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0003_remove_ipress_monitor_remove_ipress_responsable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipress',
            name='codigo',
            field=models.CharField(max_length=50, verbose_name='Código único'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='monitor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Monitor'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='responsable',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsable de la Ipress'),
        ),
    ]
